### ISSUE TITLE
TNKNavigationKit.framework 这个framework 在哪里下载？

### ISSUE THREAD

**Issue by long-fu** [tencentmap-mobility/mapmobilitydemo-iOS#1]
一直缺少TNKNavigationKit.framework 导致项目不可以运行。

**Comment by mikedpzhang** [comment]
定位SDK地址： https://github.com/tencentmap-mobility/TencentNaviDemo_iOS/releases/tag/v5.2.7.11
导航SDK地址：https://github.com/tencentmap-mobility/TencentNaviDemo_iOS/releases/tag/v5.3.0
